apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/tasks
    type: DirectoryOrCreate
