apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depolyment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: natecox/kub-demo-users
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
